swagger: "2.0"

info:
  title: "Tinyo API"
  version: "1.0"

basePath: /v1.0

paths:
  /bets/:
    get:
      operationId: app.Api.read_bets
      responses:
        '200':
          description: 'Fetch a list of bets'
          schema:
            type: array
            items:
              $ref: '#/definitions/Bet'
  /bet:
    post:
      operationId: app.Api.create_bet
      parameters:
        - in: body
          description: "parameter"
          name: bet
          schema:
            $ref: '#/definitions/Bet'
      responses:
        '200':
          description: 'Ok'
  /teams/:
    get:
      operationId: app.Api.read_teams
      responses:
        '200':
          description: 'Fetch a list of teams'
          schema:
            type: array
            items:
              $ref: '#/definitions/Team'



definitions:
  Bet:
    type: object
    properties:
      id:
        type: integer
        format: int64
      fixture:
        type: integer
        default: null

      win: {type: boolean}
      odds:
        type: number
        format: float

  Team:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: { type: string }
      league: {type: string}
  Fixture:
    type: object
    properties:
      id:
        type: integer
        format: int64
      teamHome: {type: integer}
      teamAway: {type: integer}
      date: {type: string}