swagger: "2.0"

info:
  title: "Tinyo API"
  version: "1.0"

basePath: /v1.0

paths:
  /bets/:
    get:
      responses:
        '200':
          description: 'Fetch a list of asd'
          schema:
            type: array
            items:
              $ref: '#/definitions/Bet'
  /teams/:
    get:
      responses:
        '200':
          description: 'Fetch a list of teams'
          schema:
            type: array
            items:
              $ref: '#/definitions/Team'
  /fixtures/:
    get:
      responses:
        '200':
          description: 'Fetch a list of fixtures'
          schema:
            type: array
            items:
              $ref: '#/definitions/Fixture'


definitions:
  Bet:
    type: object
    properties:
      id:
        type: integer
        format: int64
      fixture: {type: integer}
      win: {type: boolean}
  Team:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: { type: string }
      league: {type: string}
  Fixture:
    type: object
    properties:
      id:
        type: integer
        format: int64
      teamHome: {type: integer}
      teamAway: {type: integer}
      date: {type: string}